language: node_js

node_js:
  - "node"
  - "8"
  - "7"
  - "6"

cache: yarn

install:
  - yarn --frozen-lockfile --production=false
  - yarn global add codecov

script:
  - yarn lint
  - yarn test
  - codecov
